version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - ./:/var/www/html:ro
            - ./docker/web/certs/example.com.crt:/opt/certs/example.com.crt:ro
            - ./docker/web/certs/example.com.key:/opt/certs/example.com.key:ro
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - ap
        links:
            - ap
    ap:
        build: ./docker/ap
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        links:
            - db
    db:
        image: mysql
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mypH7CMS_db
          MYSQL_USER: mypH7CMS_user
          MYSQL_PASSWORD:  mypH7CMS_password
