version: '3'

services:
    web:
        image: nginx:alpine
        ports:
            - 8080:80
            - 8443:443
        volumes:
            - ./:/var/www/html
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - ap
        links:
            - ap
    ap:
        build: ./docker/ap
        volumes:
            - ./:/var/www/html
        depends_on:
            - db
        links:
            - db
    db:
        image: mysql/mysql-server:8.0.3-rc-1.1.2
        ports:
          - 8001:3306
        environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mypH7CMS_db
          MYSQL_USER: mypH7CMS_user
          MYSQL_PASSWORD:  mypH7CMS_password
